  project:
    type: website
    output-dir: _site
    resources:
      - images
  
  website:
    favicon: images/favicon.png
    title: "Scott Murff"
    navbar:
      left:
        - text: "Teaching"
          href: teaching.qmd
        - text: "Research"
          href: research.qmd
        - text: "Students"
          href: students.qmd
      right:
        - text: "Ventures"
          href: ventures.qmd
        - text: "Essays"
          href: essays/index.qmd
        - text: "About"
          href: about.qmd

    page-footer:
      center: |
        <a href="https://www.linkedin.com/in/scottdmurff/" target="_blank"><i class="bi bi-linkedin"></i></a>&nbsp;&nbsp;
        <a href="https://github.com/sdmurff" target="_blank"><i class="bi bi-github"></i></a>
        <br>
        Â© 2026 Scott Murff
  
  format:
    html:
      toc: true
      toc-location: left
      theme:
        - flatly
        - styles.scss
